### ISSUE TITLE
fails with single quotes

### ISSUE THREAD

**Issue by hunterloftis** [reworkcss/rework-npm#5]
This works:

``` css
@import "lib/message.css";
```

This doesn't:

``` css
@import 'lib/message.css';
```

```
/Users/hunter/recurly/workflow/node_modules/rework-npm/node_modules/resolve/lib/sync.js:32
    throw new Error("Cannot find module '" + x + "' from '" + y + "'");
          ^
Error: Cannot find module ''lib/message.css'' from '/Users/hunter/code/workflow-test/node_modules/asset-test'
    at Function.module.exports [as sync] (/Users/hunter/recurly/workflow/node_modules/rework-npm/node_modules/resolve/lib/sync.js:32:11)
    at resolveImport (/Users/hunter/recurly/workflow/node_modules/rework-npm/index.js:69:24)
    at getImport (/Users/hunter/recurly/workflow/node_modules/rework-npm/index.js:74:16)
    at /Users/hunter/recurly/workflow/node_modules/rework-npm/index.js:35:28
```

**Comment by conradz** [comment]
Fixed in v0.4.1
